// <auto-generated />
namespace Saturn_Budgeter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addcategorytobudgetitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcategorytobudgetitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201712051857226_add category to budget item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
